"""Reference sequences and constants for the SynBio 2026 GFP challenge."""

# 20 standard amino acids
AA20 = "ACDEFGHIKLMNPQRSTVWY"
AA_SET = set(AA20)

# Competition rules
MIN_LEN = 220
MAX_LEN = 250

# Reference sequences (from "AAseqs of 5 GFP proteins_20260511.txt")
#
# CORRECTION (2026-05-27): The competition organisers issued a correction notice
# stating the original distributed sfGFP reference contained an erroneous extra
# 'I' near position 171 (making it 239 aa). The canonical sfGFP is 238 aa,
# consistent with FPbase. The 238-aa sequence below is the corrected/official
# reference. All position numbering in this codebase is now canonical
# avGFP/sfGFP numbering (1..238). The `canon_to_comp` helper in
# thermostability.py is now an identity function.
#
# Archived old (erroneous 239-aa) version for audit trail:
# SFGFP_239_ERRONEOUS = (
#     "MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRH"
#     "DFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIK"
#     "ANFKIRHNIVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
# )  # 239 aa — DO NOT USE; superseded by the 238-aa canonical version below.
SFGFP = (
    "MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRH"
    "DFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIK"
    "ANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
)
assert len(SFGFP) == 238, f"sfGFP must be 238 aa (canonical); got {len(SFGFP)}"

AVGFP = (
    "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRYPDHMKQH"
    "DFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIK"
    "VNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
)

AMACGFP = (
    "MSKGEELFTGIVPVLIELDGDVHGHKFSVRGEGEGDADYGKLEIKFICTTGKLPVPWPTLVTTLSYGILCFARYPEHMKMN"
    "DFFKSAMPEGYIQERTIFFQDDGKYKTRGEVKFEGDTLVNRIELKGMDFKEDGNILGHKLEYNFNSHNVYIMPDKANNGLK"
    "VNFKIRHNIEGGGVQLADHYQTNVPLGDGPVLIPINHYLSCQTAISKDRNETRDHMVFLEFFSACGHTHGMDELYK"
)

CGREGFP = (
    "MTALTEGAKLFEKEIPYITELEGDVEGMKFIIKGEGTGDATTGTIKAKYICTTGDLPVPWATILSSLSYGVFCFAKYPRHI"
    "ADFFKSTQPDGYSQDRIISFDNDGQYDVKAKVTYENGTLYNRVTVKGTGFKSNGNILGMRVLYHSPPHAVYILPDRKNGGM"
    "KIEYNKAFDVMGGGHQMARHAQFNKPLGAWEEDYPLYHHLTVWTSFGKDPDDDETDHLTIVEVIKAVDLETYR"
)

PPLUGFP = (
    "MPAMKIECRITGTLNGVEFELVGGGEGTPEQGRMTNKMKSTKGALTFSPYLLSHVMGYGFYHFGTYPSGYENPFLHAINNG"
    "GYTNTRIEKYEDGGVLHVSFSYRYEAGRVIGDFKVVGTGFPEDSVIFTDKIIRSNATVEHLHPMGDNVLVGSFARTFSLRD"
    "GGYYSFVVDSHMHFKSAIHPSILQNGGPMFAFRRVEELHSNTELGIVEYQHAFKTPIAFA"
)

REFERENCE_SEQS = {
    "sfGFP": SFGFP,
    "avGFP": AVGFP,
    "amacGFP": AMACGFP,
    "cgreGFP": CGREGFP,
    "ppluGFP": PPLUGFP,
}

# Chromophore-forming residues in sfGFP/avGFP (S65/T65, Y66, G67) — 0-indexed: 64,65,66
# DO NOT mutate these or you destroy fluorescence.
CHROMOPHORE_POS_0IDX = (64, 65, 66)

# Critical chromophore-environment residues (1-indexed positions in avGFP/sfGFP numbering)
# Mutations here are very high-risk; we only allow vetted ones.
CHROMOPHORE_ENV_1IDX = {
    65, 66, 67,           # T-Y-G chromophore triad
    94, 96,               # H148 hbond network neighbours
    148, 165, 167, 203,   # canonical chromophore microenvironment
    222, 224,
}

# sfGFP differs from avGFP at the "superfolder" positions:
# Known superfolder mutations on top of avGFP/cycle3:
# S30R, Y39N, F64L, S65T, F99S, N105T, Y145F, M153T, V163A, I171V, A206V
SFGFP_SUPERFOLDER_POSITIONS_1IDX = (30, 39, 64, 65, 99, 105, 145, 153, 163, 171, 206)
